// Code generated by sqlc. DO NOT EDIT.

package device_store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Devices, error)
	DeleteDevice(ctx context.Context, deviceID uuid.UUID) error
	DeleteUserDevices(ctx context.Context, userID uuid.UUID) error
	GetDevice(ctx context.Context, deviceID uuid.UUID) (Devices, error)
	GetPaginatedUserDevices(ctx context.Context, arg GetPaginatedUserDevicesParams) (Devices, error)
	GetUserDevices(ctx context.Context, userID uuid.UUID) (Devices, error)
	ListDevices(ctx context.Context) ([]Devices, error)
	ListPaginatedDevices(ctx context.Context, arg ListPaginatedDevicesParams) ([]Devices, error)
	UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Devices, error)
	UpdateUserDevice(ctx context.Context, arg UpdateUserDeviceParams) (Devices, error)
}

var _ Querier = (*Queries)(nil)
